/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ffmplayerplus_ESNetSdkRecode */

#ifndef _Included_com_example_ffmplayerplus_ESNetSdkRecode
#define _Included_com_example_ffmplayerplus_ESNetSdkRecode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ffmplayerplus_ESNetSdkRecode
 * Method:    ES_NET_Recode_start
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_ffmplayerplus_ESNetSdkRecode_ES_1NET_1Recode_1start
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_ffmplayerplus_ESNetSdkRecode
 * Method:    ES_NET_Recode_startRecode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_ffmplayerplus_ESNetSdkRecode_ES_1NET_1Recode_1startRecode
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_example_ffmplayerplus_ESNetSdkRecode
 * Method:    ES_NET_Recode_stopRecode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ffmplayerplus_ESNetSdkRecode_ES_1NET_1Recode_1stopRecode
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
