/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ffmplayerplus_ESNetSdk */

#ifndef _Included_com_example_ffmplayerplus_ESNetSdk
#define _Included_com_example_ffmplayerplus_ESNetSdk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ffmplayerplus_ESNetSdk
 * Method:    ES_NET_setSurface
 * Signature: (Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_example_ffmplayerplus_ESNetSdk_ES_1NET_1setSurface
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_example_ffmplayerplus_ESNetSdk
 * Method:    ES_NET_start
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_ffmplayerplus_ESNetSdk_ES_1NET_1start
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_ffmplayerplus_ESNetSdk
 * Method:    ES_NET_pause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ffmplayerplus_ESNetSdk_ES_1NET_1pause
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ffmplayerplus_ESNetSdk
 * Method:    ES_NET_stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ffmplayerplus_ESNetSdk_ES_1NET_1stop
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ffmplayerplus_ESNetSdk
 * Method:    ES_NET_resume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ffmplayerplus_ESNetSdk_ES_1NET_1resume
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ffmplayerplus_ESNetSdk
 * Method:    ES_NET_capture
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_ffmplayerplus_ESNetSdk_ES_1NET_1capture
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_ffmplayerplus_ESNetSdk
 * Method:    ES_NET_startRecode
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_ffmplayerplus_ESNetSdk_ES_1NET_1startRecode
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_ffmplayerplus_ESNetSdk
 * Method:    ES_NET_stopRecode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ffmplayerplus_ESNetSdk_ES_1NET_1stopRecode
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
